---
- name: setup neutron
  hosts: neutron
  remote_user: root
  gather_facts: True
  tasks:

    - name: install neutron-plugin-ml2
      apt: 
        pkg: neutron-plugin-ml2
        state: latest

    - name: install neutron-linuxbridge-agent
      apt: 
        pkg: neutron-linuxbridge-agent
        state: latest

    - name: install neutron-l3-agent
      apt: 
        pkg: neutron-l3-agent
        state: latest

    - name: install neutron-dhcp-agent
      apt: 
        pkg: neutron-dhcp-agent
        state: latest

    - name: install neutron-metadata-agent
      apt: 
        pkg: neutron-metadata-agent
        state: latest

    - name: neutron.conf
      template: 
        src: conf/neutron.conf
        dest: /etc/neutron/neutron.conf
        owner: root 
        group: root 
        mode: 0644

    - name: ml2_conf.ini
      template: 
        src: conf/ml2_conf.ini
        dest: /etc/neutron/plugins/ml2/ml2_conf.ini
        owner: root 
        group: root 
        mode: 0644

    - name: linuxbridge_agent.ini
      template: 
        src: conf/linuxbridge_agent.ini
        dest: /etc/neutron/plugins/ml2/linuxbridge_agent.ini
        owner: root 
        group: root 
        mode: 0644

    - name: restart neutron-linuxbridge-agent
      service: 
        name: neutron-linuxbridge-agent
        state: restarted 

    - name: l3_agent.ini
      template: 
        src: conf/l3_agent.ini
        dest: /etc/neutron/l3_agent.ini
        owner: root 
        group: root 
        mode: 0644

    - name: restart neutron-l3-agent
      service: 
        name: neutron-l3-agent
        state: restarted 

    - name: dhcp_agent.ini
      template: 
        src: conf/dhcp_agent.ini
        dest: /etc/neutron/dhcp_agent.ini
        owner: root 
        group: root 
        mode: 0644

    - name: restart neutron-dhcp-agent
      service: 
        name: neutron-dhcp-agent
        state: restarted 

    - name: metadata_agent.ini
      template: 
        src: conf/metadata_agent.ini
        dest: /etc/neutron/metadata_agent.ini
        owner: root 
        group: root 
        mode: 0644

    - name: restart neutron-metadata-agent
      service: 
        name: neutron-metadata-agent
        state: restarted 