---
- name: setup keystone
  hosts: keystone
  remote_user: root
  gather_facts: True
  tasks:

    - name: install keystone
      apt: 
        pkg: keystone
        state: latest

    - name: install apache2
      apt: 
        pkg: apache2
        state: latest

    - name: install libapache2-mod-wsgi
      apt: 
        pkg: libapache2-mod-wsgi
        state: latest

    - name: keystone.conf
      template: 
        src: conf/keystone.conf
        dest: /etc/keystone/keystone.conf
        owner: root 
        group: root 
        mode: 0644

    - name: apache2.conf
      template: 
        src: conf/apache2.conf
        dest: /etc/apache2/apache2.conf
        owner: root
        group: root 
        mode: 0644

    - name: restart apache2
      service: 
        name: apache2
        state: restarted 