---
- name: setup common
  hosts: all
  remote_user: root
  gather_facts: True
  tasks:

    - name: apt upgrade
      apt:
        upgrade: dist

    - name: install python-openstackclient
      apt:
        pkg: python-openstackclient
        state: latest

    - name: install chrony
      apt:
        pkg: chrony
        state: latest

    - name: controller chrony.conf
      template:
        src: conf/controller-chrony.conf
        dest: /etc/chrony/chrony.conf
        owner: root
        group: root
        mode: 0644
      when: my_m_ip == controller_m_ip

    - name: chrony.conf
      template:
        src: conf/chrony.conf
        dest: /etc/chrony/chrony.conf
        owner: root
        group: root
        mode: 0644
      when: my_m_ip != controller_m_ip

    - name: restart chrony
      service:
        name: chrony
        state: restarted